# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
  armhf: "ghcr.io/home-assistant/armhf-base:latest"
  armv7: "ghcr.io/home-assistant/armv7-basen:latest"
labels:
  org.opencontainers.image.title: "Next Explorer"
  org.opencontainers.image.description: "Next Explorer"
  org.opencontainers.image.source: "https://github.com/bob-tm/ha-apps/next-explorer"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
