name: Next Explorer
version: "1.1.0"
slug: nextexplorer
description: Next Explorer 
url: "https://github.com/bob-tm/ha-apps/tree/main/nextexplorer"
arch:
  - aarch64
  - amd64
init: false
startup: application
ports:
  3000/tcp: 3000
map:
  - addon_config:rw
  - all_addon_configs:rw
  - homeassistant_config:rw
  - ssl:rw
  - media:rw
  - backup:rw
  - addons:rw
  - share:rw 
apparmor: false
privileged:
  - SYS_ADMIN
options:
  public_url: ""
  root_volumes: 
    - share
    - media
    - backup
  auth_mode: "both"
  mounts:
    - server: "//192.168.1.100/share1"
      name: "nas_media"
      username: "user"
      password: "password"
  log_level: info 
schema:
  root_volumes: 
    - str
  log_level: list(trace|debug|info|warn|error)
  public_url: str?
  auth_mode: list(both|local|oidc|disabled)
  mounts:
    - server: str
      name: str
      username: str
      password: str
