name: Build Add-ons

on:
  push:
    branches:
      - main
    paths:
      - "**/config.yaml"     # Сценарий запустится ТОЛЬКО если изменился config.yaml любого аддона
      - "**/config.json"

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      changed_addons: ${{ steps.changed.outputs.addons }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed add-ons
        id: changed
        uses: home-assistant/actions/helpers/find-addons@master

  build:
    needs: init
    if: ${{ needs.init.outputs.changed_addons != '[]' }}
    strategy:
      matrix:
        addon: ${{ fromJson(needs.init.outputs.changed_addons) }}
    uses: home-assistant/actions/.github/workflows/builder.yaml@master
    with:
      addon: ${{ matrix.addon }}
      images: |
        ghcr.io/${{ github.repository_owner }}/${{ matrix.addon }}-{arch}
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
